name: Fedstryale's Home
permalink: /:year/:month/:day/:title/
author: fedstryale
markdown: rdiscount
pygments: true
paginate: 16
auto: true
safe: true
weibo: fedstryale
email: fedstryale@gmail.com
duoshuo: fedstryale
