name: Fedstryale's Home
permalink: /:year/:month/:day/:title/
url: http://blog.fedstryale.info
author: fedstryale
markdown: rdiscount
pygments: true
paginate: 16
safe: true
weibo: fedstryale
email: fedstryale@gmail.com
duoshuo: fedstryale
